/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bigdata_dastor_release_DastorCryptor */

#ifndef _Included_com_bigdata_dastor_release_DastorCryptor
#define _Included_com_bigdata_dastor_release_DastorCryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bigdata_dastor_release_DastorCryptor
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/ClassLoader;)I
 */
JNIEXPORT jint JNICALL Java_com_bigdata_dastor_release_DastorCryptor_init
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_bigdata_dastor_release_DastorCryptor
 * Method:    getClassData
 * Signature: (Ljava/lang/String;Ljava/lang/ClassLoader;Ljava/lang/ClassLoader;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_com_bigdata_dastor_release_DastorCryptor_getClassData
  (JNIEnv *, jclass, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif

